@apiurl = http://localhost:3001/api
# @apiurl = https://prf-production.up.railway.app/api/users

post {{apiurl}}/users/login
content-type: application/json

{
	"username":"admin",
	"password":"matyi"
}

###
post {{apiurl}}/users/register
content-type: application/json

{
	"username":"admin2",
	"password":"matyi"
}

###

post {{apiurl}}/users/logout

###

get {{apiurl}}/users/me


### SONGS

get {{apiurl}}/songs/all
###

get {{apiurl}}/songs/my